# Generated by Django 4.2.1 on 2023-05-05 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('Fam', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('Lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('INN', models.IntegerField()),
                ('OGRN', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BankCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('INN', models.IntegerField()),
                ('OGRN', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fam', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('Lastname', models.CharField(max_length=200)),
                ('PassportSeria', models.CharField(max_length=15)),
                ('PassportCode', models.IntegerField()),
                ('Kem_Vid', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('Fam', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('Lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('Fam', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('Lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.bankcompany')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductType', models.CharField(max_length=400)),
                ('Description', models.CharField(max_length=400)),
                ('Sum', models.CharField(max_length=200)),
                ('Percent', models.IntegerField()),
                ('Months', models.IntegerField()),
                ('Link', models.CharField(max_length=200)),
                ('PrincipalCompany', models.IntegerField()),
                ('BeneficiarCompany', models.IntegerField()),
                ('AgentDecision', models.CharField(max_length=50, null=True)),
                ('PlatformDecision', models.CharField(max_length=50, null=True)),
                ('BankDecision', models.CharField(max_length=50, null=True)),
                ('Status', models.CharField(max_length=50, null=True)),
                ('UstavDoc', models.FileField(upload_to='files')),
                ('Buhotch', models.FileField(upload_to='files')),
                ('AgentWorker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.agentaccount')),
                ('BankWorkerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.bankaccount')),
                ('PlatformWorkerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.platformaccount')),
            ],
        ),
        migrations.AddField(
            model_name='agentaccount',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.agentcompany'),
        ),
    ]
