# Generated by Django 4.2.1 on 2023-05-23 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_agentworker_application_agentworkerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiarCompany',
            fields=[
                ('Name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('INN', models.IntegerField()),
                ('OGRN', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalCompany',
            fields=[
                ('Name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('INN', models.IntegerField()),
                ('OGRN', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='agentaccount',
            old_name='Lastname',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='Lastname',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Lastname',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='platformaccount',
            old_name='Lastname',
            new_name='LastName',
        ),
        migrations.AlterField(
            model_name='application',
            name='BeneficiarCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.beneficiarcompany'),
        ),
        migrations.AlterField(
            model_name='application',
            name='PrincipalCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.principalcompany'),
        ),
    ]
