# Generated by Django 4.2.1 on 2023-05-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_beneficiarcompany_principalcompany_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Percent',
            field=models.IntegerField(null=True),
        ),
    ]
