# Generated by Django 4.2.1 on 2023-05-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_application_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiarcompany',
            name='OGRN',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='principalcompany',
            name='OGRN',
            field=models.IntegerField(null=True),
        ),
    ]
