# Generated by Django 4.2.1 on 2023-05-31 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_beneficiarcompany_ogrn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarcompany',
            name='Vlad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Rank',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='principalcompany',
            name='Vlad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='Description',
            field=models.CharField(max_length=800),
        ),
    ]
