# Generated by Django 4.2.1 on 2023-05-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_beneficiarcompany_vlad_person_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Rank',
        ),
    ]
