# Generated by Django 4.2.1 on 2023-05-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_person_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Rank',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
