# Generated by Django 4.2.1 on 2023-06-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_account_remove_bankaccount_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='AgCompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.agentcompany'),
        ),
        migrations.AlterField(
            model_name='account',
            name='BankCompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.bankcompany'),
        ),
    ]
