# Generated by Django 4.2.1 on 2023-06-02 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_rename_lastname_profile_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('INN', models.IntegerField()),
                ('OGRN', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='AgCompany',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='BankCompany',
        ),
        migrations.DeleteModel(
            name='AgentCompany',
        ),
        migrations.DeleteModel(
            name='BankCompany',
        ),
        migrations.AddField(
            model_name='profile',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
    ]
