# Generated by Django 4.2.1 on 2023-06-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_company_remove_profile_agcompany_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='WorkerId',
            field=models.ManyToManyField(to='account.profile'),
        ),
    ]
