# Generated by Django 4.2.1 on 2023-06-04 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_application_workerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Date_Vid',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
