# Generated by Django 4.2.1 on 2023-06-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_person_birthday_person_date_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Buhotch',
            field=models.FileField(null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='application',
            name='UstavDoc',
            field=models.FileField(null=True, upload_to='files'),
        ),
    ]
