# Generated by Django 4.2.1 on 2023-06-06 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_application_agentdecision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='AgentDecision',
        ),
        migrations.RemoveField(
            model_name='application',
            name='BankDecision',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Buhotch',
        ),
        migrations.RemoveField(
            model_name='application',
            name='PlatformDecision',
        ),
        migrations.RemoveField(
            model_name='application',
            name='UstavDoc',
        ),
        migrations.AlterField(
            model_name='application',
            name='Description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='ProductType',
            field=models.CharField(blank=True, default='bg', max_length=400),
        ),
        migrations.AlterField(
            model_name='beneficiarcompany',
            name='OGRN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiarcompany',
            name='Vlad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.person'),
        ),
        migrations.AlterField(
            model_name='principalcompany',
            name='Vlad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.person'),
        ),
    ]
