# Generated by Django 4.2.1 on 2023-06-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_remove_application_agentdecision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='WorkerId',
        ),
    ]
